name : Check new issue
on: workflow_dispatch
    # issue_comment:
    #     types: [created, deleted]
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output GitHub context
              run: echo "${{toJson(github)}}"